version: '3'

services:
  # 主节点的容器
  redis-server-master:
    image: redis:3.0.0
    container_name: redis-server-master
    restart: always
    network_mode: redisNet
    ports:
      - 6379:6379
    # 指定时区，保证容器内时间正确
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      # 映射配置文件和数据目录
      - ./redisMaster.conf:/usr/local/etc/redis/redis.conf
      - ./redisMaster:/data
    #sysctls:
      # 必要的内核参数
      #net.core.somaxconn: '511'
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
  # 从节点1的容器
  redis-server-slave-1:
    image: redis:3.0.0
    container_name: redis-server-slave-1
    restart: always
    ports:
      - 6380:6379
    network_mode: redisNet
    depends_on:
      - redis-server-master
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - ./redisSlave1.conf:/usr/local/etc/redis/redis.conf
      - ./redisslave1:/data
    #sysctls:
      #net.core.somaxconn: '511'
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
  # 从节点2的容器
  redis-server-slave-2:
    image: redis:3.0.0
    container_name: redis-server-slave-2
    restart: always
    ports:
      - 6381:6379
    network_mode: redisNet
    depends_on:
      - redis-server-master
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - ./redisSlave2.conf:/usr/local/etc/redis/redis.conf
      - ./redisSlave2:/data
    #sysctls:
      #net.core.somaxconn: '511'
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]