version: '3'
services:
  sentinel1:
    image: redis:3.0.0
    container_name: redis-sentinel-1
    restart: always
    network_mode: redisNet
    ports:
      - 26379:26379
    # 指定时区，保证容器内时间正确
    environment:
      TZ: "Asia/Shanghai"
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    volumes:
      - ./sentinel1.conf:/usr/local/etc/redis/sentinel.conf
  sentinel2:
    image: redis:3.0.0
    container_name: redis-sentinel-2
    restart: always
    network_mode: redisNet
    ports:
      - 26380:26379
    # 指定时区，保证容器内时间正确
    environment:
      TZ: "Asia/Shanghai"
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    volumes:
      - ./sentinel2.conf:/usr/local/etc/redis/sentinel.conf
  sentinel3:
    image: redis:3.0.0
    container_name: redis-sentinel-3
    restart: always
    network_mode: redisNet
    ports:
      - 26381:26379
    # 指定时区，保证容器内时间正确
    environment:
      TZ: "Asia/Shanghai"
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    volumes:
      - ./sentinel3.conf:/usr/local/etc/redis/sentinel.conf